# https://docs.confluent.io/platform/current/connect/index.html#what-is-kafka-connect
bootstrap.servers=127.0.0.1:9092
key.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false
# Sempre deixamos a chave interna em JsonConverter
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter.schemas.enable=false
# REST API
rest.port=8086
rest.host.name=127.0.0.1
# Configuracao somente para o standalone worker
offset.storage.file.filename=standalone.offsets
offset.flush.interval.ms=10000
# Plugins do Kafka Connector
#plugin.path=/Users/lucifer/kafka_2.13-3.7.0/connectors
