# Configurações padrões do Kafka Connect, necessário para todos os connectors
name=FileStreamSinkConnector
connector.class=org.apache.kafka.connect.file.FileStreamSourceConnector
tasks.max=1

# Configurações do próprio FileStreamSourceConnector
file=demo-file.txt
topic=demo-1
